import assert from 'node:assert/strict';
import {launchSilentBrowser} from './tests/silent-browser.mjs';
import {installNativeMock} from './tests/native-mock.mjs';
const browser=await launchSilentBrowser();
try{
  const page=await browser.newPage();await page.addInitScript(installNativeMock,{});
  await page.goto(process.env.WHISPERA_TEST_URL||'http://127.0.0.1:5190');
  await page.getByRole('button',{name:'Actualizaciones',exact:true}).click();
  await page.getByText('Versión instalada: 0.2.15').waitFor();
  await page.getByRole('button',{name:'Buscar actualizaciones',exact:true}).click();
  await page.getByText('Ya tenés la última versión.').waitFor();
  await page.evaluate(()=>{window.failUpdateCheck=true;});
  await page.getByRole('button',{name:'Buscar actualizaciones',exact:true}).click();
  await page.getByRole('alert').waitFor();
  await page.evaluate(()=>{window.failUpdateCheck=false;window.nextUpdate=true;});
  await page.getByRole('button',{name:'Buscar actualizaciones',exact:true}).click();
  await page.getByText('Disponible: 0.2.16').waitFor();
  assert.equal(await page.getByRole('alert').count(),0);
  await page.getByText('Qué cambió', {exact:true}).click();await page.getByText('Herramientas corregidas',{exact:true}).waitFor();
  await page.evaluate(()=>{window.updateWorkActive=true;});
  await page.getByRole('button',{name:'Actualizar y reiniciar',exact:true}).click();
  await page.getByRole('alert').waitFor();
  assert.equal(await page.evaluate(()=>window.updateStatus.phase),'available','active work must not start installation');
  await page.evaluate(()=>{window.updateWorkActive=false;});
  await page.getByRole('button',{name:'Actualizar y reiniciar',exact:true}).click();
  await page.getByRole('progressbar',{name:'Descarga de actualización'}).waitFor();
  assert.equal(await page.getByRole('progressbar').getAttribute('value'),'50');
  assert.equal(await page.getByRole('button',{name:'Descargando…'}).isDisabled(),true);
  await page.screenshot({path:'../../.local/update-progress-download.png'});
  assert.equal(await page.locator('.desktop-sidebar').getByRole('button',{name:'Actualización disponible'}).count(),1);
  await page.evaluate(()=>{window.updateStatus={...window.updateStatus,phase:'available'};window.emitNative('updater-status',window.updateStatus,'main');});
  await page.getByRole('button',{name:'Capturas y video',exact:true}).click();
  await page.getByRole('button',{name:'Actualización disponible',exact:true}).waitFor();
  await page.getByRole('button',{name:'Actualización disponible',exact:true}).click();
  await page.getByText('Disponible: 0.2.16').waitFor();
  await page.evaluate(()=>{window.updateStatus={...window.updateStatus,phase:'verifying'};window.emitNative('updater-status',window.updateStatus,'main');});
  await page.getByText('Verificando el instalador',{exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Verificando…',exact:true}).isDisabled(),true);
  await page.evaluate(()=>{window.updateStatus={...window.updateStatus,phase:'installing'};window.emitNative('updater-status',window.updateStatus,'main');});
  await page.getByText('Instalando actualización',{exact:true}).waitFor();
  await page.screenshot({path:'../../.local/update-progress-installing.png'});
  await page.evaluate(()=>window.emitNative('updater-open',null,'main'));
  await page.getByText('Disponible: 0.2.16').waitFor();
  console.log('PASS: current/new updates, network retry, active-work guard, download/verification/install progress, persistent sidebar notice and tray navigation. IPC mocked.');
}finally{await browser.close();}
