import assert from 'node:assert/strict';
import {launchSilentBrowser} from './tests/silent-browser.mjs';
import {installNativeMock} from './tests/native-mock.mjs';
const browser=await launchSilentBrowser();
try {
  const page=await browser.newPage({viewport:{width:1100,height:850}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(installNativeMock,{});
  await page.goto((process.env.WHISPERA_TEST_URL || 'http://127.0.0.1:5190') + '/');
  await page.getByRole('button',{name:'Atajos',exact:true}).click();
  const video=page.locator('#shortcut-video'),image=page.locator('#shortcut-image');
  await video.click();await page.locator('.hotkey-field[data-listening="true"]').waitFor();
  await page.keyboard.down('Alt');assert.equal(await video.inputValue(),'Alt + …');
  await page.keyboard.press('KeyX');await page.keyboard.up('Alt');
  assert.equal(await video.inputValue(),'Alt + X');
  await image.click();await image.locator('..').filter({has:page.locator('input')}).waitFor();
  await page.waitForFunction(()=>document.querySelector('#shortcut-image').parentElement.dataset.listening==='true');
  await page.keyboard.press('Control+Shift+KeyS');assert.equal(await image.inputValue(),'Ctrl + Shift + S');
  await page.keyboard.press('Escape');assert.equal(await image.inputValue(),'Ctrl + Shift + F10','Escape restores original shortcut');
  await image.click();await page.waitForFunction(()=>document.querySelector('#shortcut-image').parentElement.dataset.listening==='true');
  await page.keyboard.press('Control+Alt+F7');await page.keyboard.press('Tab');
  assert.equal(await image.inputValue(),'Ctrl + Alt + F7');
  await page.getByRole('button',{name:'Guardar',exact:true}).click();
  await page.getByText('Los cuatro atajos quedaron guardados.').waitFor();
  assert.deepEqual(await page.evaluate(()=>window.videoPreferences),{audio:'none',hotkey:'Alt+KeyX',image_hotkey:'Control+Alt+F7',frame_color:'#ffffff',image_auto_copy:false});
  const captures=await page.evaluate(()=>window.calls.filter(c=>c.command==='shortcut_capture').map(c=>c.args.active));
  assert.ok(captures.includes(true));assert.equal(captures.at(-1),false);
  assert.ok(!await page.evaluate(()=>window.calls.some(c=>['screen_select','screen_start','recording_action'].includes(c.command))));
  const voice=page.locator('#shortcut-voice');await voice.click();
  await page.waitForFunction(()=>document.querySelector('#shortcut-voice').parentElement.dataset.listening==='true');
  await page.keyboard.press('Alt+KeyZ');assert.equal(await voice.inputValue(),'Alt + Z');
  await page.keyboard.press('Shift');assert.equal(await voice.inputValue(),'Alt + Z','a modifier alone never overwrites the shortcut');
  await page.evaluate(()=>window.dispatchEvent(new Event('blur')));
  await page.waitForFunction(()=>window.calls.filter(c=>c.command==='shortcut_capture').at(-1).args.active===false);
  await image.click();await page.waitForFunction(()=>document.querySelector('#shortcut-image').parentElement.dataset.listening==='true');
  await image.dispatchEvent('keyup',{key:'PrintScreen',code:'PrintScreen',bubbles:true});
  assert.equal(await image.inputValue(),'Impr Pant','Print Screen works with keyup only');
  await image.dispatchEvent('keyup',{key:'PrintScreen',code:'',ctrlKey:true,bubbles:true});
  assert.equal(await image.inputValue(),'Ctrl + Impr Pant','Missing physical code falls back to named key');
  await image.dispatchEvent('keydown',{key:'PrintScreen',code:'PrintScreen',altKey:true,bubbles:true});
  await image.dispatchEvent('keyup',{key:'PrintScreen',code:'PrintScreen',bubbles:true});
  assert.equal(await image.inputValue(),'Alt + Impr Pant','Release must not overwrite modifiers captured on keydown');
  await page.keyboard.press('Escape');
  assert.equal(await image.inputValue(),'Ctrl + Alt + F7','Print Screen edit still supports cancellation');
  await image.click();await page.waitForFunction(()=>document.querySelector('#shortcut-image').parentElement.dataset.listening==='true');
  await image.dispatchEvent('keyup',{key:'PrintScreen',code:'PrintScreen',bubbles:true});
  await page.keyboard.press('Tab');
  await page.getByRole('button',{name:'Guardar',exact:true}).click();
  await page.waitForFunction(()=>window.videoPreferences.image_hotkey==='PrintScreen');
  assert.deepEqual(errors,[]);
  console.log('PASS: pressed combinations for voice/video/image, plus formatting, modifier-only input, Escape rollback, focus release, persistence, editable white-default border.');
} finally {await browser.close();}
