import assert from 'node:assert/strict';
import {launchSilentBrowser} from './tests/silent-browser.mjs';
import { PNG } from 'pngjs';
import { installNativeMock } from './tests/native-mock.mjs';
const browser=await launchSilentBrowser();
try {
  const page=await browser.newPage({viewport:{width:640,height:480}}), errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(installNativeMock,{kind:'image',width:640,height:480,scale:2});
  await page.goto((process.env.WHISPERA_TEST_URL || 'http://127.0.0.1:5190') + '/overlay.html?view=screen-ink');
  const canvas=page.getByLabel('Editar captura');await canvas.waitFor();
  await page.waitForFunction(()=>window.calls.some(c=>c.command==='screen_editor_ready'));
  assert.equal(await page.locator('.screen-image-frame').evaluate(e=>getComputedStyle(e).borderColor),'rgb(255, 255, 255)');
  const preview=PNG.sync.read(await page.screenshot());
  assert.deepEqual(Array.from(preview.data.subarray((preview.width+100)*4,(preview.width+100)*4+3)),[255,255,255],'white border remains visible above the screenshot');
  await page.keyboard.press('a');await page.mouse.move(50,50);await page.mouse.down();await page.mouse.move(200,120);await page.mouse.up();
  await page.waitForFunction(()=>window.feedback.count===1);
  await page.keyboard.press('Control+z');await page.waitForFunction(()=>window.feedback.count===0&&window.feedback.canRedo);
  await page.keyboard.press('Control+Shift+z');await page.waitForFunction(()=>window.feedback.count===1);
  await page.keyboard.press('t');await page.mouse.click(70,170);await page.getByLabel('Texto de la marca').fill('Prueba');await page.keyboard.press('Enter');
  await page.waitForFunction(()=>window.feedback.count===2);
  await page.keyboard.press('v');await page.mouse.move(90,180);await page.mouse.down();await page.mouse.move(150,240);await page.mouse.up();
  await page.keyboard.press('Delete');await page.waitForFunction(()=>window.feedback.count===1);
  await page.keyboard.press('Control+z');await page.waitForFunction(()=>window.feedback.count===2);
  await page.keyboard.press('Shift+Delete');await page.waitForFunction(()=>window.feedback.count===0);
  await page.keyboard.press('Control+y');assert.equal(await page.evaluate(()=>window.feedback.count),0);
  await page.keyboard.press('Control+z');await page.waitForFunction(()=>window.feedback.count===2);
  await page.evaluate(()=>{window.failExport=true;});await page.keyboard.press('Control+c');
  await page.waitForFunction(()=>window.feedback.error.includes('Portapapeles'));assert.equal(await page.evaluate(()=>window.feedback.count),2);
  await page.evaluate(()=>{window.failExport=false;});await page.keyboard.press('Control+c');await page.waitForFunction(()=>window.exports.length===1);
  const bytes=await page.evaluate(()=>window.exports[0].bytes), png=PNG.sync.read(Buffer.from(bytes));
  assert.equal(png.width,1280);assert.equal(png.height,960);
  const pixel=(x,y)=>Array.from(png.data.subarray((y*png.width+x)*4,(y*png.width+x)*4+4));
  assert.deepEqual(pixel(10,10),[238,238,238,255]);assert.ok(pixel(100,100)[0]>240&&pixel(100,100)[1]<160,'red annotation remains in exported PNG');
  assert.deepEqual(pixel(1,1),[238,238,238,255],'preview border is excluded from the PNG export');
  await page.keyboard.press('b');await page.mouse.move(300,300);await page.mouse.down();await page.mouse.move(420,370);await page.mouse.up();
  await page.waitForFunction(()=>window.feedback.count===3&&!window.feedback.busy);
  await page.keyboard.press('Control+z');await page.waitForFunction(()=>window.feedback.count===2);
  await page.keyboard.press('Control+y');await page.waitForFunction(()=>window.feedback.count===3);
  await page.goto((process.env.WHISPERA_TEST_URL || 'http://127.0.0.1:5190') + '/overlay.html?view=screen-tools');
  await page.setViewportSize({width:76,height:604});await page.getByLabel('Herramientas de captura').waitFor();
  const toolbar=await page.getByLabel('Herramientas de captura').boundingBox();assert.ok(toolbar.y+toolbar.height<=604&&toolbar.x+toolbar.width<=76,'toolbar fits native window');
  await page.getByLabel('Flecha',{exact:true}).click();assert.ok(await page.evaluate(()=>window.calls.some(c=>c.command==='screen_editor_action'&&c.args.action.value==='arrow')));
  await page.setViewportSize({width:350,height:604});
  await page.getByRole('button',{name:'Grosor',exact:true}).click();
  await page.getByRole('button',{name:'Grosor grueso'}).click();
  assert.ok(await page.evaluate(()=>window.calls.some(c=>c.command==='screen_editor_action'&&c.args.action.action==='width'&&c.args.action.value==='8')));
  assert.equal(await page.getByRole('combobox').count(),0,'stroke sizes use visual buttons');
  await page.screenshot({path:'../../.local/editor-toolbar.png'});
  await page.goto((process.env.WHISPERA_TEST_URL || 'http://127.0.0.1:5190') + '/overlay.html?view=screen-hud');
  await page.setViewportSize({width:297,height:56});await page.getByLabel('Acciones de captura').waitFor();
  await page.getByRole('button',{name:'Copiar',exact:true}).click();
  assert.ok(await page.evaluate(()=>window.calls.some(c=>c.command==='screen_editor_action'&&c.args.action.action==='copy')));
  const video=await browser.newPage({viewport:{width:640,height:480}});await video.addInitScript(installNativeMock,{kind:'video'});
  await video.goto((process.env.WHISPERA_TEST_URL || 'http://127.0.0.1:5190') + '/overlay.html?view=screen-ink');await video.getByLabel('Dibujar sobre video').waitFor();
  await video.waitForFunction(()=>window.calls.some(c=>c.command==='screen_editor_ready'));
  assert.equal(await video.locator('canvas').evaluate(el=>el.getContext('2d').getImageData(0,0,1,1).data[3]),0);
  await video.keyboard.press('p');await video.mouse.move(40,40);await video.mouse.down();await video.mouse.move(140,90,{steps:8});await video.mouse.up();
  await video.waitForFunction(()=>window.feedback.count===1);await video.keyboard.press('v');await video.waitForFunction(()=>window.feedback.tool==='pointer');
  await video.keyboard.press('b');await video.mouse.move(200,200);await video.mouse.down();await video.mouse.move(330,280);await video.mouse.up();
  await video.waitForFunction(()=>window.feedback.count===2&&!window.feedback.busy);
  assert.ok(await video.evaluate(()=>window.calls.some(c=>c.command==='screen_editor_sample')));
  const mask=await video.locator('canvas').evaluate(el=>{const ctx=el.getContext('2d');return{middle:Array.from(ctx.getImageData(260,240,1,1).data),corner:Array.from(ctx.getImageData(200,200,1,1).data)};});
  assert.equal(mask.middle[3],255,'blur mask remains opaque over changing video');assert.equal(mask.corner[3],0,'blur corners are rounded');
  await video.keyboard.press('Escape');assert.ok(await video.evaluate(()=>window.calls.some(c=>c.command==='screen_escape')));
  await video.goto((process.env.WHISPERA_TEST_URL || 'http://127.0.0.1:5190') + '/overlay.html?view=screen-tools');await video.getByLabel('Herramientas de captura').waitFor();
  assert.equal(await video.getByRole('button',{name:'Copiar',exact:true}).count(),0);
  assert.equal(await video.getByRole('button',{name:/detener/i}).count(),0);
  assert.equal(await video.getByText(/Esc.*atajo/i).count(),0,'video footer hint was removed');
  await video.getByRole('button',{name:'Puntero / seleccionar'}).click();
  assert.ok(await video.evaluate(()=>window.calls.some(c=>c.command==='screen_editor_action'&&c.args.action.value==='pointer')));
  await video.getByRole('button',{name:'Contraer herramientas'}).click();
  assert.equal(await video.getByRole('toolbar',{name:'Dibujo'}).count(),0);
  await video.getByRole('button',{name:'Expandir herramientas'}).click();
  await video.getByRole('toolbar',{name:'Dibujo'}).waitFor();
  assert.deepEqual(errors,[]);
  console.log('PASS: annotations, text, move/delete, undo/redo, clear recovery, clipboard failure recovery, PNG pixels and DPI, toolbar fit, transparent video ink and pointer mode (mocked IPC).');
} finally {await browser.close();}
