import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { installNativeMock } from './tests/native-mock.mjs';
const browser = await chromium.launch({ headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1100, height: 800 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(installNativeMock,{});
  await page.goto('http://127.0.0.1:5190/');
  await page.getByRole('button', { name: 'Capturas y video', exact: true }).click();
  assert.equal(await page.locator('#screen-audio').inputValue(), 'none');
  await page.locator('#screen-audio').selectOption('both');
  await page.locator('#screen-hotkey').click();
  await page.locator('.hotkey-field[data-listening="true"]').waitFor();
  await page.keyboard.press('Control+Alt+F8');
  assert.equal(await page.locator('#screen-hotkey').inputValue(),'Ctrl + Alt + F8');
  assert.equal(await page.locator('#screen-frame-color').inputValue(),'#ffffff');
  await page.getByRole('button', { name: 'Guardar preferencias', exact: true }).click();
  await page.getByText('Preferencias de pantalla guardadas.').waitFor();
  assert.deepEqual(await page.evaluate(() => window.videoPreferences), { audio: 'both', hotkey: 'Control+Alt+F8', image_hotkey:'Control+Shift+F10', frame_color:'#ffffff' });
  await page.getByRole('button', { name: 'Seleccionar área y grabar' }).click();
  assert.ok(await page.evaluate(() => window.calls.some(c => c.command === 'screen_select')));
  await page.goto('http://127.0.0.1:5190/?view=screen-select');
  await page.locator('.screen-selection').waitFor();
  await page.mouse.move(600, 450); await page.mouse.down(); await page.mouse.move(200, 200); await page.mouse.up();
  await page.waitForFunction(()=>window.calls.some(c=>c.command==='screen_start'));
  const selection = await page.evaluate(() => window.calls.find(c => c.command === 'screen_start'));
  assert.deepEqual(selection.args.rect, { x: 200, y: 200, width: 400, height: 250 });
  await page.getByTestId('recording-frame').waitFor();
  assert.equal(await page.evaluate(()=>performance.getEntriesByType('navigation').length),1);
  assert.ok(page.url().endsWith('?view=screen-select'), 'selection becomes an indicator without navigating');
  await page.evaluate(()=>window.emitNative('screen-reset','video'));
  await page.locator('.screen-selection').waitFor();
  await page.goto('http://127.0.0.1:5190/?view=screen-select');
  await page.locator('.screen-selection').waitFor();
  await page.mouse.move(200, 200); await page.mouse.down(); await page.mouse.move(203, 204); await page.mouse.up();
  await page.getByText('Seleccioná un área más grande.').waitFor();
  assert.equal(await page.evaluate(() => window.calls.some(c => c.command === 'screen_start')), false);
  await page.keyboard.press('Escape');
  assert.ok(await page.evaluate(() => window.calls.some(c => c.command === 'screen_cancel_selection')));
  await page.goto('http://127.0.0.1:5190/?view=screen-indicator&x=200&y=200&width=400&height=250');
  await page.evaluate(() => { window.videoStatus = { phase: 'recording', seconds: 65, path: '', error: '', copied: false }; });
  await page.getByText('Grabando video').waitFor();
  await page.getByLabel('Tiempo grabado').filter({ hasText: '01:05' }).waitFor();
  assert.equal(await page.getByRole('button').count(), 0);
  const frame = await page.getByTestId('recording-frame').boundingBox();
  assert.deepEqual(frame, { x: 200, y: 200, width: 400, height: 250 });
  assert.equal(await page.locator('[data-slot="folder"]').count(), 1);
  assert.equal(await page.locator('.screen-indicator').evaluate(el => getComputedStyle(el).pointerEvents), 'none');
  await page.evaluate(() => { window.videoStatus = { phase: 'saving', seconds: 65, path: '', error: '', copied: false }; });
  await page.getByText('Preparando video').waitFor();
  assert.equal(await page.getByTestId('recording-frame').count(), 0);
  await page.goto('http://127.0.0.1:5190/?view=screen-indicator&x=850&y=0&width=200&height=250');
  await page.evaluate(() => { window.videoStatus = { phase: 'recording', seconds: 1, path: '', error: '', copied: false }; });
  await page.getByText('Grabando video').waitFor();
  const folder = await page.locator('.screen-folder-indicator').boundingBox();
  assert.ok(folder.y >= 8 + 180 * .85, 'reserve space for the cards above the folder');
  assert.ok(folder.x >= 8 && folder.x + folder.width <= 1092);
  assert.ok(folder.y + folder.height <= 792);
  await page.goto('http://127.0.0.1:5190/');
  await page.getByRole('button', { name: 'Capturas y video', exact: true }).click();
  await page.evaluate(() => { window.videoStatus = { phase: 'idle', seconds: 65, path: 'temporary.mp4', error: '', copied: true }; });
  await page.getByText('Video copiado. Pegalo con Ctrl+V.').waitFor();
  await page.getByRole('button', { name: 'Copiar video', exact: true }).click();
  assert.ok(await page.evaluate(() => window.calls.some(c => c.command === 'screen_copy')));
  assert.deepEqual(errors, []);
  console.log('PASS: preferences, selection, Escape, persistent frame, shared folder animation, click-through styling, no recording buttons, saving state, and clipboard actions (mocked IPC).');
} finally { await browser.close(); }
